spring:
  datasource:
    #url:  jdbc:h2:tcp://localhost/~/Projects/extra/db/testdb
    url: jdbc:h2:mem:productiondb
    username: sa
    password: test
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      defer-datasource-initialization: true
    #    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

jwt:
  secret: rWAvFa2Xi5FuhLPK5cIMk4m6FxhbIKTzsrBKz4
